### ISSUE TITLE
Docker Issue creating database

### ISSUE THREAD

**Issue by My-Random-Thoughts** [ellite/Wallos#1]
Hey, running exact docker command (but with actual paths) results in the following error message:

```
[10-Nov-2023 13:46:28] NOTICE: fpm is running, pid 7
[10-Nov-2023 13:46:28] NOTICE: ready to handle connections
Database does not exist. Creating it...
sh: syntax error: unexpected "("

Fatal error: Uncaught TypeError: Unsupported operand types: SQLite3 - string in /var/www/html/endpoints/cronjobs/createdatabase.php:98
Stack trace:
#0 {main}
  thrown in /var/www/html/endpoints/cronjobs/createdatabase.php on line 98
```

I get the registration page but the "Main Currency" drop down is empty and when registering I get these errors:

```
Warning: Undefined array key "main_currency" in /var/www/html/registration.php on line 30

Warning: SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /var/www/html/registration.php on line 44
```

**Comment by ellite** [comment]
Thank you for the report.

It's fixed with this commit: https://github.com/ellite/Wallos/commit/2e55e105b555986c55701805a73eea997e92ed41

Please remove `wallos.db` from your mounted `/path/to/config/wallos/db` and pull the latest docker image again.

Please let me know if it worked.

**Comment by esmoyer** [comment]
The currency selector is there now but still getting `Warning: SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /var/www/html/registration.php on line 44` when attempting to register.

**Comment by ellite** [comment]
The startup script now add permissions to the database after creating the database. https://github.com/ellite/Wallos/commit/21a2776b390d906dfafc997d55204f428795a656

if you pull the latest image it should now work 🤞

**Comment by ellite** [comment]
I've been able to replicate it. I will come back to you as soon as I find a fix.
Sorry about that.

**Comment by esmoyer** [comment]
No worries at all. Just saw this mentioned on the self.hosted Friday post so was eager to check it out!

**Comment by ellite** [comment]
Should be fixed: https://github.com/ellite/Wallos/commit/e4b8b8d4a09f8844ad4a4ab7a4e5e319e7bc6424
As always please pull the latest image from dockerhub.

**Comment by esmoyer** [comment]
It works! Thanks for the quick work!!

**Comment by My-Random-Thoughts** [comment]
Working for me too now.  Thank you for your quick response.
