### ISSUE TITLE
BUG.Add category, refresh without name

### ISSUE THREAD

**Issue by Axe-l** [ellite/Wallos#233]
Add category, refresh no name
![image](https://github.com/ellite/Wallos/assets/45731066/60660ba3-e446-4c8f-93c6-614f8b71edc1)

![image](https://github.com/ellite/Wallos/assets/45731066/87aae2d6-97d5-4a38-ae66-a71fc0f86e49)

**Comment by ellite** [comment]
Hi, thank you for the report.
Should be fixed on 1.16.3

Regards

**Comment by Axe-l** [comment]
The problem remains with 1.16.3
![image](https://github.com/ellite/Wallos/assets/45731066/e29afb6a-11d5-4936-b4ff-0ce4e9a3c6cd)
![image](https://github.com/ellite/Wallos/assets/45731066/c67c29b3-b845-4e93-88cd-4e3cae795ed6)

**Comment by ellite** [comment]
Do you get any message when you press the save button?
Can you open the developer tools and see if there's some error on the console?

Thanks .
