### ISSUE TITLE
[BUG] Ampersand (&) in title or description are displayed as &amp;

### ISSUE THREAD

**Issue by FunnyPocketBook** [ellite/Wallos#266]
Wallos version: 1.19.0
Installation: Docker (docker compose)
Host system: Unraid v6.12.6

### Expected Behaviour
- An ampersand `&` is rendered as `&`

### Actual Behaviour
- An ampersand `&` is rendered as `&amp;`

### Steps to reproduce
1. Create a new subscription or edit any existing one
2. Add an ampersand (`&`) to any text field 
3. Save the subscription
4. The ampersand is now displayed as `&amp;`

### Additional info
Since an ampersand is also present in the `&amp;`, every time the subscription is saved, a new `amp;` shows up. 

### Screenshots
![image](https://github.com/ellite/Wallos/assets/30187411/1f6ab99d-e702-4f45-94bd-18bc35f53946)
![image](https://github.com/ellite/Wallos/assets/30187411/13b0861c-94ec-442a-855f-61f31d94fe3e)

**Comment by ellite** [comment]
Hi. Thank you for the report. I'll try to fix it.

**Comment by DanteB918** [comment]
> Hi. Thank you for the report. I'll try to fix it.

`htmlspecialchars_decode()` should do the trick, it just escapes the HTML so `&amp;` would be `&` 😄

Hope this helps!

https://www.php.net/manual/en/function.htmlspecialchars-decode.php

**Comment by ellite** [comment]
Thank you. I'll check.

**Comment by ellite** [comment]
Should be fixed with 1.20.1
You need to edit the subscription and replace &amp; with &

Regards.

And thank you @DanteB918 for the suggestion.

**Comment by FunnyPocketBook** [comment]
Thanks, that worked! However, the other text fields (e.g. notes or URL) are still showing the same. Could you also call the function for those fields?

**Comment by ellite** [comment]
Ah, of course. Forgot about those.
I will fix it.
